name: Skiddy's Build Job

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-pio-${{ hashFiles('platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-pio-

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build
        run: pio run

      - name: Prepare binaries
        run: |
          mkdir -p release_bin
          cp .pio/build/esp32-c3-devkitm-1/firmware.bin release_bin/SkidBGone_ESP32C3.bin
          cp .pio/build/m5stick-c-plus2/firmware.bin release_bin/SkidBGone_M5StickCPlus2.bin

      - name: Upload binaries artifact
        uses: actions/upload-artifact@v4
        with:
          name: SkidBGone_Firmwares
          path: release_bin/*.bin

      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          name: "SkidBGone ${{ github.ref_name }}"
          files: release_bin/*.bin
